using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

/// <summary>
/// Central registry for all 15 Phase C spacecraft parts.
/// - Scene-configured prefabs (wire, magnetometer) are registered directly.
/// - Missing items are generated by cloning the template prefab so all
///   components (ItemDragHandler, CircleCollider2D, etc.) are present.
/// - Each item gets a small runtime-generated colored disc on its SpriteRenderer
///   (world display) and the full art sprite on its Image (inventory/UI display).
/// </summary>
public class ItemDictionary : MonoBehaviour
{
    [Tooltip("Assign item prefabs here (at minimum the base item.prefab and WireItem.prefab). " +
             "IDs are assigned automatically based on list order (index 0 = ID 1, etc.).")]
    public List<Item> itemPrefabs;

    private Dictionary<int, GameObject> itemDictionary = new Dictionary<int, GameObject>();

    // ─── Item definitions ────────────────────────────────────────────────────
    // id, display name, art-sprite resource path, world-disc colour
    private static readonly (int id, string name, string artPath, Color color)[] AllItems =
    {
        (1,  "Magnetometer Parts", "MinigameC/Items/item_magnetometer_parts", new Color(0.20f, 0.85f, 1.00f)),
        (2,  "Wiring",             "MinigameC/Items/item_wiring",             new Color(1.00f, 0.60f, 0.20f)),
        (3,  "Camera Sensor",      "MinigameC/Items/item_camera_sensor",      new Color(0.30f, 0.50f, 1.00f)),
        (4,  "Spectrometer Core",  "MinigameC/Items/item_spectrometer_core",  new Color(0.70f, 0.30f, 1.00f)),
        (5,  "Insulation",         "MinigameC/Items/item_insulation",         new Color(0.20f, 0.90f, 0.40f)),
        (6,  "Metal Alloy",        "MinigameC/Items/item_metal_alloy",        new Color(0.75f, 0.75f, 0.80f)),
        (7,  "Circuit Board",      "MinigameC/Items/item_circuit_board",      new Color(0.40f, 1.00f, 0.30f)),
        (8,  "Coffee",             "MinigameC/Items/item_coffee",             new Color(0.55f, 0.28f, 0.10f)),
        (9,  "Energy Bar",         "MinigameC/Items/item_energy_bar",         new Color(1.00f, 0.85f, 0.10f)),
        (10, "Solar Cells",        "MinigameC/Items/item_solar_cells",        new Color(1.00f, 0.78f, 0.00f)),
        (11, "Battery",            "MinigameC/Items/item_battery",            new Color(0.00f, 0.85f, 0.85f)),
        (12, "Radio Antenna",      "MinigameC/Items/item_radio_antenna",      new Color(1.00f, 0.40f, 0.70f)),
        (13, "Laser Module",       "MinigameC/Items/item_laser_module",       new Color(1.00f, 0.20f, 0.30f)),
        (14, "Navigation System",  "MinigameC/Items/item_navigation_system",  new Color(0.40f, 0.80f, 1.00f)),
        (15, "Propellant",         "MinigameC/Items/item_propellant",         new Color(0.90f, 0.30f, 0.90f)),
    };

    // ─── Unity lifecycle ─────────────────────────────────────────────────────

    void Awake()
    {
        itemDictionary = new Dictionary<int, GameObject>();

        // Assign sequential IDs to scene-configured prefabs
        for (int i = 0; i < itemPrefabs.Count; i++)
            if (itemPrefabs[i] != null)
                itemPrefabs[i].ID = i + 1;

        // Register scene-configured prefabs
        foreach (Item item in itemPrefabs)
        {
            if (item == null) continue;
            itemDictionary[item.ID] = item.gameObject;
            item.displayName = LookupName(item.ID);
        }

        // Assign correct world disc + art sprites to registered prefabs
        foreach (var kv in new Dictionary<int, GameObject>(itemDictionary))
            ApplySprites(kv.Value, kv.Key);

        // Build any missing IDs by cloning the template
        GenerateMissingItems();
    }

    // ─── Sprite application ──────────────────────────────────────────────────

    /// <summary>
    /// Sets a small runtime-generated colored disc on the SpriteRenderer (world view)
    /// and the full art sprite on the Image component (inventory/UI view).
    /// </summary>
    private void ApplySprites(GameObject go, int id)
    {
        if (go == null) return;

        Sprite art = LoadArtSprite(LookupArtPath(id));

        // ── World sprite: art image assigned directly (PhaseCWorldItemUI scales it) ──
        SpriteRenderer sr = go.GetComponent<SpriteRenderer>();
        if (sr == null) sr = go.AddComponent<SpriteRenderer>();
        sr.sprite       = art != null ? art : CreateWorldSprite(LookupColor(id));
        sr.color        = Color.white;
        sr.sortingOrder = 10;

        // Pre-scale the GameObject immediately so items never flash at raw sprite size
        // while waiting for PhaseCWorldItemUI.Initialize() to run (up to 0.5 s delay).
        // PhaseCWorldItemUI recomputes this same scale when it initialises, so no conflict.
        const float worldDisplaySize = 0.8f;
        if (sr.sprite != null && sr.sprite.pixelsPerUnit > 0f && sr.sprite.rect.width > 0f)
        {
            float naturalSize = sr.sprite.rect.width / sr.sprite.pixelsPerUnit;
            if (naturalSize > 0f)
                go.transform.localScale = Vector3.one * (worldDisplaySize / naturalSize);
        }

        // ── Art sprite: full item art (Image, shown inside inventory Canvas) ──
        Image img = go.GetComponent<Image>();
        if (img != null && art != null)
            img.sprite = art;

        // ── Display name ────────────────────────────────────────────────────
        Item item = go.GetComponent<Item>();
        if (item != null)
            item.displayName = LookupName(id);
    }

    // ─── Missing-item generation ─────────────────────────────────────────────

    private void GenerateMissingItems()
    {
        // Use the first scene prefab as a template so we clone ALL components
        // (ItemDragHandler, CircleCollider2D, material, sorting layer, etc.)
        Item template = null;
        foreach (Item p in itemPrefabs)
            if (p != null) { template = p; break; }

        if (template == null)
        {
            Debug.LogError("ItemDictionary: No template prefab found. " +
                           "Please assign at least one item prefab in the Inspector.");
            return;
        }

        foreach (var def in AllItems)
        {
            if (itemDictionary.ContainsKey(def.id)) continue;

            // Clone template — inherits ItemDragHandler, collider, sorting layer, etc.
            GameObject itemGo = Instantiate(template.gameObject);
            itemGo.name = def.name;
            itemGo.SetActive(false);

            // Patch metadata
            Item item = itemGo.GetComponent<Item>();
            item.ID          = def.id;
            item.displayName = def.name;

            // Assign sprites
            ApplySprites(itemGo, def.id);

            // Register
            itemDictionary[def.id] = itemGo;
            while (itemPrefabs.Count < def.id) itemPrefabs.Add(null);
            itemPrefabs[def.id - 1] = item;
        }
    }

    // ─── Sprite creation helpers ─────────────────────────────────────────────

    /// <summary>
    /// Generates a 48×48 anti-aliased disc sprite with a bright rim.
    /// PPU = 48 so the sprite's natural world size = 1×1 unit.
    /// PhaseCWorldItemUI scales it to 0.5 world units (worldScale = 0.5).
    /// </summary>
    public static Sprite CreateWorldSprite(Color baseColor)
    {
        const int   size    = 48;
        const float ppu     = 48f;
        Texture2D   tex     = new Texture2D(size, size, TextureFormat.RGBA32, false);
        tex.filterMode = FilterMode.Bilinear;

        float cx      = (size - 1) * 0.5f;
        float outerR  = size * 0.46f;
        float borderW = 3.5f;

        for (int y = 0; y < size; y++)
        for (int x = 0; x < size; x++)
        {
            float d = Mathf.Sqrt((x - cx) * (x - cx) + (y - cx) * (y - cx));

            if (d > outerR)
            {
                tex.SetPixel(x, y, Color.clear);
            }
            else if (d > outerR - borderW)
            {
                // Bright rim
                float t     = (d - (outerR - borderW)) / borderW;
                Color rimC  = Color.Lerp(baseColor * 1.5f, new Color(1f, 1f, 1f, 0.95f), t);
                tex.SetPixel(x, y, rimC);
            }
            else
            {
                // Body: light centre → base colour towards edge
                float t     = d / (outerR - borderW);
                Color inner = Color.Lerp(Color.Lerp(Color.white, baseColor, 0.25f), baseColor, t);
                tex.SetPixel(x, y, inner);
            }
        }

        tex.Apply();
        return Sprite.Create(tex, new Rect(0, 0, size, size), new Vector2(0.5f, 0.5f), ppu);
    }

    /// <summary>Loads a sprite from Assets/Resources using LoadAll so multi-sprite sheets work.</summary>
    private static Sprite LoadArtSprite(string path)
    {
        if (string.IsNullOrEmpty(path)) return null;
        Sprite s = Resources.Load<Sprite>(path);
        if (s != null) return s;
        Sprite[] all = Resources.LoadAll<Sprite>(path);
        return (all != null && all.Length > 0) ? all[0] : null;
    }

    // ─── Lookup helpers ──────────────────────────────────────────────────────

    private string LookupName(int id)
    {
        foreach (var def in AllItems) if (def.id == id) return def.name;
        return $"Item {id}";
    }

    private Color LookupColor(int id)
    {
        foreach (var def in AllItems) if (def.id == id) return def.color;
        return Color.white;
    }

    private string LookupArtPath(int id)
    {
        foreach (var def in AllItems) if (def.id == id) return def.artPath;
        return string.Empty;
    }

    // ─── Public API ──────────────────────────────────────────────────────────

    public GameObject GetItemPrefab(int itemId)
    {
        if (itemDictionary.TryGetValue(itemId, out GameObject go)) return go;
        Debug.LogWarning($"ItemDictionary: Item ID {itemId} not found.");
        return null;
    }

    public string GetDisplayName(int itemId) => LookupName(itemId);

    /// <summary>Returns the tint colour for a given item (used by world UI for glow).</summary>
    public Color GetItemColor(int itemId) => LookupColor(itemId);
}
